const QUOTES = {
  morning: [
    "Good morning. ready to ship?",
    "Coffee first, code later.",
    "Make it work, make it right, make it fast.",
    "Another day, another commit.",
    "Wake up and crush it.",
    "The best way to predict the future is to invent it.",
    "Focus on being productive instead of busy.",
    "Early bird gets the bug.",
  ],
  afternoon: [
    "Keep pushing.",
    "Stay focused.",
    "Don't stop when you're tired. Stop when you're done.",
    "Simplicity is the soul of efficiency.",
    "Code never lies, comments sometimes do.",
    "Refactor, optimize, repeat.",
    "You are doing great.",
    "Take a deep breath and debug.",
  ],
  evening: [
    "Unwind and reflect.",
    "Great work today.",
    "Rest is part of the process.",
    "Commit your changes and relax.",
    "Is it time to deploy to production? (Maybe not).",
    "Prepare for tomorrow.",
    "Recharge your batteries.",
  ],
  night: [
    "Go to sleep.",
    "Late night coding? Drink water.",
    "The bug will be there tomorrow.",
    "Sleep is the best debugger.",
    "Working late or hardly working?",
    "Eyes off screen, time to dream.",
    "Shut down.",
  ],
  anytime: [
    "Hello, friend.",
    "Time to build.",
    "Minimalism is key.",
    "Stay curious.",
    "Talk is cheap. Show me the code.",
    "It works on my machine.",
    "Just ship it.",
  ],
};
