const QUOTES = {
  morning: [
    "Good morning. ready to ship?",
    "Coffee first, code later.",
    "Make it work, make it right, make it fast.",
    "Another day, another commit.",
    "Wake up and crush it.",
    "The best way to predict the future is to invent it.",
    "Focus on being productive instead of busy.",
    "Early bird gets the bug.",
    "Stand-up soon. Be ready.",
    "Small steps today, big wins tomorrow.",
    "Start clean: write tests first.",
    "Fresh day, fresh branch.",
    "Ship early, iterate often.",
    "One task. One focus.",
    "Build momentum, not excuses.",
    "Morning sync: align and execute.",
  ],
  afternoon: [
    "Keep pushing.",
    "Stay focused.",
    "Don't stop when you're tired. Stop when you're done.",
    "Simplicity is the soul of efficiency.",
    "Code never lies, comments sometimes do.",
    "Refactor, optimize, repeat.",
    "You are doing great.",
    "Take a deep breath and debug.",
    "Progress over perfection.",
    "Halfway there. Keep going.",
    "Fix the root cause, not the symptom.",
    "Measure twice, deploy once.",
    "Bugs fear focused engineers.",
    "Make it readable for future you.",
    "One more test, one less regret.",
    "Stay calm and trace the logs.",
  ],
  evening: [
    "Unwind and reflect.",
    "Great work today.",
    "Rest is part of the process.",
    "Commit your changes and relax.",
    "Is it time to deploy to production? (Maybe not).",
    "Prepare for tomorrow.",
    "Recharge your batteries.",
    "Wrap up loose ends.",
    "Push your final commit.",
    "Write the README while it's fresh.",
    "Celebrate the small wins.",
    "Good code deserves good rest.",
    "Leave a note for tomorrow-you.",
    "End the day with clean diffs.",
    "Slow down, you're still ahead.",
  ],
  night: [
    "Go to sleep.",
    "Late night coding? Drink water.",
    "The bug will be there tomorrow.",
    "Sleep is the best debugger.",
    "Working late or hardly working?",
    "Eyes off screen, time to dream.",
    "Shut down.",
    "No heroics. Sleep.",
    "Tomorrow you will thank you.",
    "Close the laptop. Close the loop.",
    "Logs can wait. Rest can't.",
    "Stop chasing perfection at 2 AM.",
    "Save your work. Save yourself.",
    "Night mode: offload and recover.",
    "You've done enough for today.",
  ],
  anytime: [
    "Hello, friend.",
    "Time to build.",
    "Minimalism is key.",
    "Stay curious.",
    "Talk is cheap. Show me the code.",
    "It works on my machine.",
    "Just ship it.",
    "Make it simple, then make it better.",
    "Solve the problem, not the keyboard.",
    "If it's hard to explain, it's hard to maintain.",
    "Automate the boring stuff.",
    "Quality is a habit.",
    "Write code your team can trust.",
    "Keep your PRs small.",
    "Work in silence, let the results talk.",
    "Debug like a detective.",
    "Think in systems.",
  ],
};
